language: python

python:
  - "3.7"

install:
  - make install

stages:
  - lint
  - unittest

jobs:
  include:
    - stage: lint
      script: make lint
    - stage: unittest
      script: export PYTHONPATH=$(pwd)/app && make unittest
